import { execSync } from 'child_process';
import crypto from 'crypto';
import fs from 'fs';
import os from 'os';
import path from 'path';
import readline from 'readline';

const isYes = process.argv.includes('--yes') || process.argv.includes('-y') || !process.stdin.isTTY;

function ask(rl: readline.Interface, query: string, defaultVal: string = ''): Promise<string> {
  if (isYes) {
    return Promise.resolve(defaultVal);
  }
  return new Promise((resolve) => {
    const promptText = defaultVal ? `${query} [${defaultVal}]: ` : `${query}: `;
    rl.question(promptText, (ans) => {
      resolve(ans.trim() || defaultVal);
    });
  });
}

function askPassword(query: string, defaultVal: string = ''): Promise<string> {
  if (isYes || !process.stdin.setRawMode) {
    return Promise.resolve(defaultVal);
  }
  return new Promise((resolve) => {
    const promptText = defaultVal ? `${query} [${defaultVal}]: ` : `${query}: `;
    process.stdout.write(promptText);

    let password = '';
    const wasRaw = process.stdin.isRaw;
    process.stdin.setRawMode(true);
    process.stdin.resume();

    const onData = (chunk: Buffer) => {
      const str = chunk.toString('utf8');
      for (let i = 0; i < str.length; i++) {
        const char = str[i];
        if (char === '\r' || char === '\n') {
          cleanup();
          process.stdout.write('\n');
          resolve(password.trim() || defaultVal);
          return;
        } else if (char === '\u0003') {
          cleanup();
          process.stdout.write('\n');
          process.exit(130);
        } else if (char === '\u0004') {
          cleanup();
          process.stdout.write('\n');
          resolve(password.trim() || defaultVal);
          return;
        } else if (char === '\u0008' || char === '\u007f') {
          if (password.length > 0) {
            password = password.slice(0, -1);
            process.stdout.write('\b \b');
          }
        } else if (char.charCodeAt(0) >= 32 && char.charCodeAt(0) <= 126) {
          password += char;
          process.stdout.write('*');
        }
      }
    };

    const cleanup = () => {
      process.stdin.removeListener('data', onData);
      if (process.stdin.setRawMode) {
        process.stdin.setRawMode(wasRaw || false);
      }
      process.stdin.pause();
    };

    process.stdin.on('data', onData);
  });
}

function getGitConfig(key: string): string {
  try {
    return execSync(`git config ${key}`, { encoding: 'utf8' }).trim();
  } catch {
    return '';
  }
}

function getGitRemoteUrl(remoteName: string = 'origin', cwd?: string): string {
  try {
    const cmd = cwd ? `git -C "${cwd}" remote get-url ${remoteName}` : `git remote get-url ${remoteName}`;
    return execSync(cmd, { encoding: 'utf8' }).trim();
  } catch {
    return '';
  }
}

function getSshStatus(): string {
  try {
    const home = process.env.HOME || '';
    const sshDir = path.join(home, '.ssh');
    const commonKeys = ['id_ed25519.pub', 'id_rsa.pub', 'id_ecdsa.pub'];
    for (const k of commonKeys) {
      if (fs.existsSync(path.join(sshDir, k))) {
        return `Found ~/.ssh/${k}`;
      }
    }
    const agentOut = execSync('ssh-add -l 2>/dev/null', { encoding: 'utf8' }).trim();
    if (agentOut && !agentOut.includes('no identities')) {
      return 'Loaded in ssh-agent';
    }
  } catch {}
  return 'None found (will use HTTPS / Git credential helper)';
}

function parseDotEnv(filePath: string): Record<string, string> {
  if (!fs.existsSync(filePath)) return {};
  const content = fs.readFileSync(filePath, 'utf8');
  const result: Record<string, string> = {};
  for (const line of content.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const idx = trimmed.indexOf('=');
    if (idx > 0) {
      const key = trimmed.slice(0, idx).trim();
      let val = trimmed.slice(idx + 1).trim();
      if ((val.startsWith('"') && val.endsWith('"')) || (val.startsWith("'") && val.endsWith("'"))) {
        val = val.slice(1, -1);
      }
      result[key] = val;
    }
  }
  return result;
}

function writeDotEnv(filePath: string, vars: Record<string, string>, comments: Record<string, string> = {}) {
  const lines: string[] = [
    '# .dev.vars (Git-Ignored Local Development Secrets)',
    '# Auto-generated by SlottD Briefcase Setup',
    `# Created: ${new Date().toISOString()}`,
    '',
  ];

  for (const [k, v] of Object.entries(vars)) {
    if (comments[k]) {
      lines.push(`# ${comments[k]}`);
    }
    lines.push(`${k}="${v}"`);
  }
  lines.push('');
  fs.writeFileSync(filePath, lines.join('\n'), 'utf8');
}

async function main() {
  console.log('──────────────────────────────────────────────────────────────────');
  console.log('💼  SlottD Briefcase Setup & Operator Configuration');
  console.log('──────────────────────────────────────────────────────────────────\n');

  const rootDir = process.cwd();
  const devVarsPath = path.join(rootDir, '.dev.vars');
  const existingVars = parseDotEnv(devVarsPath);

  // 1. Detect Git & SSH Environment
  const defaultGitName = getGitConfig('user.name') || existingVars.OPERATOR_NAME || 'Local Operator';
  const defaultGitEmail = getGitConfig('user.email') || existingVars.OPERATOR_EMAIL || 'dev@localhost';
  const sshStatus = getSshStatus();

  console.log(`Git User Detected:  ${defaultGitName} <${defaultGitEmail}>`);
  console.log(`SSH Remote Status:  ${sshStatus}\n`);

  let rl: readline.Interface | null = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
  });

  let tempCloneDir: string | null = null;

  try {
    // 2. Confirm Operator Identity
    console.log('1. Operator Profile (attributing local revisions & git commits)');
    const operatorName = await ask(rl, '   Operator Name', defaultGitName);
    const operatorEmail = await ask(rl, '   Operator Email', defaultGitEmail);
    console.log('');

    // 3. Security & Local Key Isolation
    console.log('2. Key Isolation & Credentials');
    console.log('   In Briefcase mode, local keys NEVER match staging or production.');
    
    let apiKey = existingVars.ADMIN_API_KEY;
    if (!apiKey || apiKey === 'test-secret' || apiKey === 'secret-test-token-123') {
      apiKey = `local-briefcase-${crypto.randomBytes(12).toString('hex')}`;
      console.log(`   ✨ Generated fresh randomized local ADMIN_API_KEY: ${apiKey}`);
    } else {
      console.log(`   ✓ Retaining existing local ADMIN_API_KEY: ${apiKey.slice(0, 16)}...`);
    }

    let jwtSecret = existingVars.JWT_SECRET;
    if (!jwtSecret) {
      jwtSecret = `jwt-${crypto.randomBytes(16).toString('hex')}`;
    }

    const hasExistingHash = !!existingVars.ADMIN_PASSWORD_HASH || !!existingVars.ADMIN_PASSWORD;
    const promptPass = hasExistingHash
      ? `Keep existing or enter new password (or type REMOVE for zero-barrier)`
      : `Set an optional local admin password (press enter for zero-barrier)`;

    rl.close();
    const adminPasswordInput = await askPassword(`   ${promptPass}`, '');
    rl = readline.createInterface({
      input: process.stdin,
      output: process.stdout,
    });

    let passwordHash = existingVars.ADMIN_PASSWORD_HASH || '';
    if (adminPasswordInput.trim().toUpperCase() === 'REMOVE') {
      passwordHash = '';
      console.log('   ✓ Removed local password (switched to zero-barrier)');
    } else if (adminPasswordInput.trim()) {
      passwordHash = crypto.createHmac('sha256', apiKey).update(adminPasswordInput.trim()).digest('hex');
      console.log('   ✓ Password hashed and encrypted at rest (HMAC-SHA256)');
    } else if (existingVars.ADMIN_PASSWORD && !passwordHash) {
      passwordHash = crypto.createHmac('sha256', apiKey).update(existingVars.ADMIN_PASSWORD).digest('hex');
    }
    console.log('');

    // 4. Git Remote Repository & Content Source (Optional)
    console.log('3. Git Remote Repository & Content Source (Optional)');
    const currentOrigin = getGitRemoteUrl('origin') || existingVars.GIT_REMOTE_URL || '';
    const promptOrigin = currentOrigin
      ? `   Git Remote URL`
      : `   Git Remote URL (e.g. git@github.com:org/repo.git or https://...) [press enter to skip]`;
    const gitRemoteUrl = await ask(rl, promptOrigin, currentOrigin);

    const neutralRepo = '/Users/bmo/code/websites-deployed/brainendeavor.com';
    const targetRepoDir = existingVars.REPO_PATH || (fs.existsSync(neutralRepo) ? neutralRepo : rootDir);
    let activeContentDir = existingVars.CONTENT_DIR || (fs.existsSync(neutralRepo) ? neutralRepo : path.join(rootDir, 'content'));

    if (gitRemoteUrl) {
      // Configure remote origin inside the dedicated content repository (never touch monorepo)
      try {
        const existingOrigin = getGitRemoteUrl('origin', targetRepoDir);
        if (!existingOrigin) {
          execSync(`git -C "${targetRepoDir}" remote add origin "${gitRemoteUrl}"`, { stdio: 'ignore' });
          console.log(`   ✓ Configured git remote 'origin' -> ${gitRemoteUrl} (in ${targetRepoDir})`);
        } else if (existingOrigin !== gitRemoteUrl) {
          execSync(`git -C "${targetRepoDir}" remote set-url origin "${gitRemoteUrl}"`, { stdio: 'ignore' });
          console.log(`   ✓ Updated git remote 'origin' -> ${gitRemoteUrl} (in ${targetRepoDir})`);
        } else {
          console.log(`   ✓ Using remote 'origin': ${gitRemoteUrl} (in ${targetRepoDir})`);
        }
      } catch (err: any) {
        console.warn('   ⚠️ Note on git remote origin:', err.message);
      }

      // Prompt to initialize content database from remote git repo
      const initFromRemote = await ask(rl, '   Initialize content database from this Git repo? (Y/n)', 'Y');
      if (initFromRemote.toLowerCase() === 'y' || initFromRemote.toLowerCase() === 'yes') {
        console.log(`   📥 Fetching content from remote repository...`);
        try {
          const currentOrigin = getGitRemoteUrl('origin');
          if (currentOrigin === gitRemoteUrl) {
            try {
              execSync('git fetch origin', { stdio: 'inherit' });
              console.log('   ✓ Remote origin successfully fetched.');
            } catch (fetchErr: any) {
              console.warn('   ⚠️ git fetch origin notice:', fetchErr.message);
            }
          } else {
            // External Git repository: shallow clone to temporary directory
            tempCloneDir = path.join(os.tmpdir(), `slottd-content-${Date.now()}`);
            console.log(`   Cloning remote content repo to temporary staging directory...`);
            execSync(`git clone --depth 1 "${gitRemoteUrl}" "${tempCloneDir}"`, { stdio: 'inherit' });

            const potentialDirs = [
              path.join(tempCloneDir, 'content'),
              path.join(tempCloneDir, 'brainendeavor-slottd-cms', 'content'),
              tempCloneDir,
            ];

            const foundDir = potentialDirs.find(
              (d) => fs.existsSync(d) && fs.readdirSync(d).some((f) => fs.statSync(path.join(d, f)).isDirectory())
            );

            if (foundDir) {
              activeContentDir = foundDir;
              console.log(`   ✓ Located content directory in remote repository: ${activeContentDir}`);
            }
          }
        } catch (err: any) {
          console.warn(`   ⚠️ Remote content fetch notice: ${err.message}. Using local content/ directory.`);
        }
      }
    }
    console.log('');

    // 5. Save to .dev.vars
    const newVars: Record<string, string> = {
      ENVIRONMENT: 'development',
      OPERATOR_NAME: operatorName,
      OPERATOR_EMAIL: operatorEmail,
      ADMIN_API_KEY: apiKey,
      JWT_SECRET: jwtSecret,
      PREVIEW_SECRET: existingVars.PREVIEW_SECRET || `preview-${crypto.randomBytes(8).toString('hex')}`,
      REPO_PATH: targetRepoDir,
      CONTENT_DIR: activeContentDir,
    };

    if (passwordHash) {
      newVars.ADMIN_PASSWORD_HASH = passwordHash;
    }

    if (gitRemoteUrl) {
      newVars.GIT_REMOTE_URL = gitRemoteUrl;
    }

    const comments: Record<string, string> = {
      OPERATOR_NAME: 'Local Briefcase operator attribution',
      ADMIN_API_KEY: 'Local-only random key (isolated from staging/prod)',
      JWT_SECRET: 'Local session secret',
      ADMIN_PASSWORD_HASH: 'HMAC-SHA256 hashed password (encrypted at rest)',
      REPO_PATH: 'Local repository root path',
      CONTENT_DIR: 'Relative content directory',
      GIT_REMOTE_URL: 'Remote Git content repository URL',
    };

    writeDotEnv(devVarsPath, newVars, comments);
    console.log(`✅ Saved local configuration to ${path.relative(rootDir, devVarsPath)}\n`);

    // 6. Run Database Migrations
    console.log('4. Initializing Local D1 Database Schema...');
    try {
      execSync('npx wrangler d1 migrations apply brainendeavor-slottd-db --local', {
        stdio: 'inherit',
        cwd: rootDir,
      });
      console.log('✅ Local D1 migrations applied successfully.\n');
    } catch (e: any) {
      console.error('⚠️ Migration warning:', e.message);
    }

    // 7. Content Hydration
    console.log(`5. Hydrating Local Database from Git Content (${activeContentDir})...`);
    try {
      execSync(`npx tsx scripts/sync-git.ts --hydrate --content-dir="${activeContentDir}"`, {
        stdio: 'inherit',
        cwd: rootDir,
      });
    } catch (e: any) {
      console.error('⚠️ Hydration warning:', e.message);
    }

    console.log('\n──────────────────────────────────────────────────────────────────');
    console.log('🎉 SlottD Briefcase is ready!');
    console.log(`   Operator:    ${operatorName} <${operatorEmail}>`);
    console.log(`   Auth Mode:   ${passwordHash ? 'Password Protected (HMAC-SHA256)' : 'Zero-Barrier (Friction-Free Local Dev)'}`);
    console.log(`   Git Remote:  ${gitRemoteUrl || 'None configured (local only)'}`);
    console.log(`   Security:    Fully isolated from staging & production`);
    console.log('\nTo launch the local Studio UI and Astro preview bridge:');
    console.log('   npm run dev');
    console.log('   Open: http://localhost:8787/admin');
    console.log('──────────────────────────────────────────────────────────────────\n');
  } finally {
    if (tempCloneDir && fs.existsSync(tempCloneDir)) {
      try {
        fs.rmSync(tempCloneDir, { recursive: true, force: true });
      } catch {}
    }
    rl?.close();
  }
}

main().catch((err) => {
  console.error('Setup failed:', err);
  process.exit(1);
});
